import streamlit as st

# App Setup
st.set_page_config(page_title="Algorithmic Aesthetics", layout="centered")

# Session State Initialization
if "ap" not in st.session_state:
    st.session_state.ap = 0
if "route" not in st.session_state:
    st.session_state.route = None
if "step" not in st.session_state:
    st.session_state.step = 0

# Helper Functions
def add_ap(value):
    st.session_state.ap += value

def next_step():
    st.session_state.step += 1

def reset():
    st.session_state.ap = 0
    st.session_state.route = None
    st.session_state.step = 0


# Header
st.title("Algorithmic Aesthetics")
st.caption("A choose-your-own-adventure story about taste, choice, and algorithms")
st.markdown(f"**Algorithm Points:** {st.session_state.ap}")
st.divider()

# Opening Scene
if st.session_state.route is None:
    st.markdown(
        """
        **Bzzzzt. Bzzzzzzt. Bzzzzzzzzzt.**

        The alarm cuts sharply through the air. Your phone vibrates against the wood of your bedside table, just loud enough to be annoying but not enough to fully wake you from your slumber. You could leave it alone, but the walls are thin and you'd feel bad for your neighbors next to you. It is a Friday, after all, and not everyone has classes today.

        You reach over to your bedside table to snooze it, but in your morning delirium, your hand misses and knocks over something hard instead. 
        
        **Splash!**

        That was your water bottle, you realize with a groan. You never closed it last night, plunking it down after a late-night study session and not bothering to twist the cap. Cold water splashes across your bed and floor, seeping into the sheets, the carpet, and your pillow.

        This was *not* the morning you had imagined last night before bed.

        What do you do?
        """
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        if st.button("Go back to bed and ignore everything, snoozing your alarm"):
            st.session_state.route = "A"
            st.session_state.step = 0
    with col2:
        if st.button("Get up and clean the spill"):
            st.session_state.route = "B"
            st.session_state.step = 0
    with col3:
        if st.button("Sit up and check your phone first"):
            st.session_state.route = "C"
            st.session_state.step = 0


# ROUTE A
if st.session_state.route == "A":

    if st.session_state.step == 0:
        st.markdown("""
        You let your head sink back into the pillow, feeling the damp chill of the water through your socks. Your phone sits next to you, buzzing quietly every few minutes. You feel an odd comfort in the routine: notifications, familiar faces, the scroll of content already tailored to your taste.

        You eventually drag yourself out of bed and stand in front of your closet. Choices lie ahead, but they feel predetermined, familiar.
        """)
        st.markdown("**Standing in front of your closet, what do you choose to wear?**")
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Wear something you saw on TikTok"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Wear something intentionally different"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Wear something that makes you feel comfortable"):
                next_step()

    elif st.session_state.step == 1:
        st.markdown("""
        Outside, the air is cool and brisk. People move past you, faces half-hidden behind earbuds, phones in hand. You pull your headphones out, the soft weight reassuring in your hands.

        Music will set the mood for the walk to class, but *which* music? The decision feels both significant and trivial at once.
        """)
        st.markdown("**Choose your music:**")
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Spotify's autogenerated Daily Mix 1"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("A playlist you painstakingly curated yourself"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Silence"):
                next_step()

    elif st.session_state.step == 2:
        st.markdown("""
        Between classes, you sit alone in a quiet corner. Your phone rests in your hand. A post slowly loads, caption first: 'You'll love this! Buy now!' It almost feels AI-generated, in a way, not fully connecting with you on a human level but clearly trying to.

        You linger on it for a second, wondering about the decisions you've made so far today. Are they *truly* yours? Someone from your dorm walks by at that exact moment, a philosophy major, in fact. Maybe they'd know something about that! But something in you doesn't *really* want to ask.
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Keep scrolling. Who cares?"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Close the app and go for a run to clear your head"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Pause and reflect, without bothering them"):
                next_step()

    elif st.session_state.step == 3:
        st.markdown("""
        Acceptance: Night descends. Lying in bed, fragments of the day replay in your mind. You wonder how much was truly you and how much was quietly arranged by unseen algorithms.
        """)
        if st.button("Continue"):
            next_step()

    elif st.session_state.step == 4:
        st.subheader("Conclusion")
        if st.session_state.ap >= 2:
            st.markdown("**You are optimized.** Life feels smooth and guided. Choices come filtered, refined, easy.")
        elif st.session_state.ap <= -2:
            st.markdown("**You are haunted.** Avoidance and resistance leave traces; the algorithm's influence echoes in habits.")
        else:
            st.markdown("**You are aware.** You use the system consciously, knowing its influence.")
        if st.button("Restart"):
            reset()


# ROUTE B
if st.session_state.route == "B":

    if st.session_state.step == 0:
        st.markdown("""
        You leap from the bed, grabbing a towel and mopping the water from the floor. The cold seeps into your socks, but the act of cleaning gives you a sense of agency.

        Your phone buzzes angrily with a text, but you don't *really* want to look at it. This is more important.
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Check the notification anyway. You'll respond eventually"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Ignore it deliberately, throwing it onto your bedsheets"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Flip your phone face-down on the table"):
                next_step()

    elif st.session_state.step == 1:
        st.markdown("""
        Later, walking to class, each step is audible on the sidewalk. Without phone distractions, the campus feels alive: the hum of conversation, the distant honk of cars, and the crisp breeze all ring in your ears. Resistance to digital guidance heightens your awareness of the world. You are *proud* of this. You're an *icon.* 
        
        You're a bit bored, though. You *could* listen to something, but it'd mean pulling your phone out of your pocket and giving in. Do you *want* to give in?
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Turn your music on anyway. One song won't hurt"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Walk proudly, without digital input"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Sing something in your head"):
                next_step()

    elif st.session_state.step == 2:
        st.markdown("""
        After class, you have nothing to do. Your clubs don't meet for another few hours, and the curiosity of that notification finally tempts you. You glance at the app. 
        
        *Ah, Instagram...*
        
        The posts look familiar, the same aesthetic flow. You feel almost... *comforted* by it.
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Scroll for a long time"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Close the app immediately"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Scroll briefly"):
                next_step()

    elif st.session_state.step == 3:
        st.markdown("Resistance: Even rejection of the algorithm does not erase its influence. Every choice has context, after all, even if it is defined by resistance.")
        if st.button("Continue"):
            next_step()

    elif st.session_state.step == 4:
        st.subheader("Conclusion")
        if st.session_state.ap >= 2:
            st.markdown("**You return.** Even resistance leads to gradual reintegration.")
        elif st.session_state.ap <= -2:
            st.markdown("**You withdraw.** Algorithm fades, but its lessons linger in habits.")
        else:
            st.markdown("**You hover.** You're neither fully inside nor fully outside the influence.")
        if st.button("Restart"):
            reset()


# ROUTE C
if st.session_state.route == "C":

    if st.session_state.step == 0:
        st.markdown("""
        You sit on the edge of your bed, observing the water spill. Your phone rests silent beside you. For a moment, the day has not yet started. 
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Pick up your phone"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Clean the spill first"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Sit and think"):
                next_step()

    elif st.session_state.step == 1:
        st.markdown("""
        Your outfit shouldn't matter that much to you, but it does. It's a reflection of your inner self, after all. What does your inner self look like?
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Choose something you saw on TikTok"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("Choose something unique"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Choose something familiar"):
                next_step()

    elif st.session_state.step == 2:
        st.markdown("""
        Walking to class, headphones in hand, you decide whether to listen to music, silence, or a song chosen deliberately. Each choice is made with awareness of guidance and personal taste.
        """)
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("Algorithmic playlist"):
                add_ap(1)
                next_step()
        with col2:
            if st.button("One deliberate song, looped over and over"):
                add_ap(-1)
                next_step()
        with col3:
            if st.button("Silence"):
                next_step()

    elif st.session_state.step == 3:
        st.markdown("Insight: understanding the shaping forces doesn’t undo them, but allows conscious navigation.")
        if st.button("Continue"):
            next_step()

    elif st.session_state.step == 4:
        st.subheader("Conclusion")
        if st.session_state.ap >= 2:
            st.markdown("**You comply knowingly.** Guided, but aware of the influence.")
        elif st.session_state.ap <= -2:
            st.markdown("**You maintain distance.** Reflective, careful, independent.")
        else:
            st.markdown("**You navigate consciously.** Influenced, but making deliberate choices.")
        if st.button("Restart"):
            reset()